In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
s23 = pd.read_csv('spotify-2023.csv', encoding='ISO-8859-1')

In [3]:
oldies = pd.read_csv('songs_normalize.csv')

In [4]:
oldies.head()

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop

In [5]:
s23.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [6]:
s23.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [7]:
s23.shape

(953, 24)

In [8]:
s23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [9]:
s23['streams'].unique()

array(['141381703', '133716286', '140003974', '800840817', '303236322',
       '183706234', '725980112', '58149378', '95217315', '553634067',
       '505671438', '58255150', '1316855716', '387570742', '2513188493',
       '1163093654', '496795686', '30546883', '335222234', '363369738',
       '86444842', '52135248', '1297026226', '200647221', '115364561',
       '78300654', '899183384', '61245289', '429829812', '127408954',
       '22581161', '52294266', '843957510', '999748277', '618990393',
       '123122413', '188933502', '1355959075', '786181836', '176553476',
       '354495408', '2808096550', '1109433169', '1047101291', '65156199',
       '570515054', '1085685420', '1647990401', '2565529693', '518745108',
       '107753850', '177740666', '153372011', '57876440', '1813673666',
       '3703895074', '256483385', '1214083358', '16011326', '812019557',
       '111947664', '156338624', '720434240', '357925728', '674072710',
       '1755214421', '404562836', '373199958', '14780425', '39578178',
       '54266102', '2557975762', '751134527', '2282771485', '1356565093',
       '1592909789', '635412045', '1230675890', '585695368', '43857627',
       '2009094673', '600976848', '39709092', '39228929', '2665343922',
       '223633238', '2887241814', '1440757818', '165484133', '58054811',
       '157058870', '95131998', '250305248', '685032533', '38411956',
       '144565150', '127567540', '399686758', '983637508', '118482347',
       '882831184', '286400165', '172825906', '1241559043', '29562220',
       '77309611', '1605224506', '1116995633', '838079900', '1163620694',
       '1093605526', '179659294', '39058561', '36912123', '1205951614',
       '1791000570', '201660859', '248088961', '90839753', '607123776',
       '55842345', '211050784', '342897938', '2762', '330346424',
       '601863821', '1953533826', '2322580122', '2355719893', '66902503',
       '96273746', '430977451', '284819874', '721975598', '1217120710',
       '109276132', '276259178', '54225632', '2559529074', '681583126',
       '2594040133', '81102253', '11956641', '1687664027', '11599388',
       '611700552', '1133865788', '1089402494', '411747614', '255932395',
       '31873544', '95053634', '1279434863', '233801632', '1481349984',
       '142095275', '618885532', '2011464183', '1167330737', '929964809',
       '436027885', '657723613', '2713922350', '621660989', '1591223784',
       '950906471', '1593270737', '1410088830', '1235005533',
       '1661187319', '1374581173', '94186466', '1788326445', '1840364617',
       '143573775', '684675814', '1113838873', '1267333350', '726307468',
       '3562543890', '1131090940', '307370144', '1271293243', '265882712',
       '841749534', '47956378', '806397070', '2132335812', '1641426668',
       '2135158446', '367316268', '350381515', '1264310836', '30343206',
       '405136812', '1145727611', '540654286', '57312735', '397582059',
       '1479115056', '86773632', '133753727', '123124076', '463564958',
       '64533040', '65496046', '68616963', '161460990', '70106975',
       '113509496', '89933133', '71007139', '43522589', '232896922',
       '37126685', '195576623', '532336353', '538115192', '46142772',
       '401036314', '127026613', '345031710', '288101651', '60350538',
       '335074782', '76767396', '46065667', '459276435', '39666245',
       '138517666', '822633917', '595900742', '51985779', '57945987',
       '115010040', '175097833', '57089066', '488386797', '32761689',
       '1047480053', '153454328', '217672943', '457184829', '939844851',
       '726434358', '573633020', '1406111294', '71573339', '24975653',
       '145458418', '1424589568', '231332117', '415932686', '988515741',
       '50847624', '39893489', '92035115', '118810253', '77233241',
       '206399629', '117747907', '266624541', '293186992', '139681964',
       '123132751', '103762518', '162887075', '91221625', '190490915',
       '96180277', '185240616', '885093467', '104992946', '147290338',
       '1302184087', '158950978', '76910644', '137123880', '782369383',
       '502574952', '207033255', '404887295', '381161027', '466231982',
       '357580552', '61105704', '198275403', '168448603', '705469769',
       '34502215', '482175240', '304118600', '1449799467', '173627354',
       '90025258', '652704649', '1829992958', '655466831', '146409671',
       '95816024', '117206995', '100409613', '80758350', '325592432',
       '58473276', '52722996', '191945597', '77377503', '743693613',
       '267789608', '1221813483', '449701773', '67070410', '116334601',
       '433356509', '165584767', '367814306', '477033549', '156214700',
       '448843705', '1357608774', '294352144', '972164968', '920045682',
       '2420461338', '1947371785', '244658767', '68216992', '223582566',
       '471819764', '272377463', '1361425037', '149778242', '116599790',
       '148469433', '497225336', '88791109', '125917280', '105062254',
       '95623148', '144584800', '298063749', '166570053', '83021468',
       '139836056', '303216294', '221409663', '58890931', '81419389',
       '156777415', '284908316', '93438910', '363472647', '372476382',
       '380726517', '56533272', '175399345', '203221468', '1624165576',
       '134294498', '70069745', '609293408', '671365962', '362361576',
       '93587665', '1223481149', '1022258230', '263453310', '1435127549',
       '236857112', '147538971', '698086140', '723894473', '34450974',
       '403097450', '309483971', '319566866', '909001996', '1061966512',
       '32526947', '124988687', '103787664', '134255790', '301051721',
       '152850295', '309653982', '297328960', '332506354', '480507035',
       '1065580332', '122763672', '445763624', '1365184', '184308753',
       '789753877', '323358833', '606361689', '120972253', '338564981',
       '1606986953', '1301799902', '140187018', '1897517891', '107642809',
       '551305895', '556585270', '2303033973', '646886885', '222612678',
       '1814349763', '872137015', '571386359', '304079786', '174006928',
       '284785823', '163284000', '246390068', '482257456', '168684524',
       '78489819', '195516622', '1260594497', '428685680', '1024858327',
       '838586769', '199386237', '972509632', '213438580', '1555511105',
       '210038833', '227918678', '826623384', '1802514301', '1329090101',
       '181831132', '462791599', '348647203', '366599607', '90598517',
       '1479264469', '1449779435', '1159176109', '769213520', '741301563',
       '807561936', '834129063', '663832097', '446390129', '690104769',
       '485285717', '520034544', '476244795', '629173063', '404664135',
       '98709329', '110849052', '460492795', '94005786', '395591396',
       '389771964', '403939487', '481697415', '110073250', '88092256',
       '351636786', '473248298', '73981293', '155653938', '429504768',
       '242767149', '65362788', '67540165', '62019074', '135723538',
       '295998468', '261116938', '136689549', '135611421', '356709897',
       '110649992', '301869854', '127027715', '57144458', '56870689',
       '323437194', '317726339', '116144341', '328207708', '608228647',
       '180577478', '809306935', '49262961', '614555082', '245350949',
       '178660459', '51641685', '78139948', '322336177', '1007612429',
       '326792833', '391251368', '349585590', '339659802', '674772936',
       '432719968', '1309887447', '119238316', '116903579', '888046992',
       '200660871', '130655803', '1887039593', '88103848', '101114984',
       '1575467011', '91656026', '1042568408', '1735441776', '726837877',
       '53933526', '267758538', '74601456', '920797189', '539595276',
       '1367810478', '578207856', '775542072', '863625566', '656013912',
       '1056760045', '611994237', '1230855859', '582981380', '1858144199',
       '240684449', '583687007', '63803529', '466214729', '236940480',
       '41924466', '225259194', '393230256', '287201015', '599770206',
       '342779426', '673801126', '1168642797', '540539717', '383550148',
       '530511203', '37307967', '510876816', '1445941661', '1763363713',
       '374191487', '108809090', '436695353', '421040617', '501541661',
       '354065229', '1143647827', '311395144', '672656250', '1256880657',
       '1692897992', '245095641', '686734357', '261414174', '610045621',
       '1115880852', '594482982', '566954746',
       'BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3',
       '374706940', '184937148', '31959571', '167076418', '824420218',
       '363467642', '1127468248', '60680939', '247737946', '1699402402',
       '154797871', '198883004', '124407432', '850608354', '376333030',
       '516784627', '1608045237', '506778838', '1472799873', '513643924',
       '261286503', '783706581', '422691058', '1062345656', '1252563873',
       '851070493', '263894529', '345903614', '951637566', '956865266',
       '427486004', '156658366', '624515457', '777765388', '412795151',
       '1138474110', '355219175', '290228626', '1062956628', '1180094974',
       '1456081449', '432702334', '489945871', '465959382', '2864791672',
       '2288695111', '720825549', '2086124197', '1690192927', '991336132',
       '593917618', '200972675', '71014967', '560222750', '1806617704',
       '77337771', '528544703', '865640097', '2159346687', '211372494',
       '651732901', '608334048', '863756573', '797402345', '1695712020',
       '1759567999', '223319934', '54937991', '226897599', '258316038',
       '596152090', '177129919', '716591492', '1210599487', '246376690',
       '496311364', '146789379', '843309044', '500340342', '107255472',
       '135079152', '822239726', '1202722675', '343197054', '240769997',
       '426204830', '421135627', '554875730', '467727006', '327498031',
       '185408548', '245400167', '579395142', '675039469', '252871192',
       '231996128', '1929770265', '918915401', '1180896317', '498960285',
       '685071800', '258714692', '143139338', '209768491', '64714573',
       '50746620', '154119539', '181328253', '370068639', '2280566092',
       '563902868', '317622165', '291709698', '203680270', '81350745',
       '282883169', '64787943', '2484812918', '461437791', '1439191367',
       '759208783', '368646862', '299634472', '756907987', '682475162',
       '546191065', '229473310', '202677468', '121913181', '208166039',
       '527033089', '94616487', '394030335', '193443895', '299648208',
       '182978249', '319757142', '109091573', '153240879', '346127840',
       '312622938', '2197010679', '1200808494', '797196073', '1970673297',
       '665765558', '263779030', '339473453', '2204080728', '2591224264',
       '135444283', '1457139296', '236872197', '694525298', '240661097',
       '421365166', '349746291', '255120451', '190981339', '924193303',
       '305771063', '273005485', '89566512', '677389855', '75476209',
       '408843328', '187772591', '178512385', '101780047', '118381354',
       '146363130', '126443991', '157990698', '176290831', '1023187129',
       '106933107', '139193812', '212234990', '1714490998', '197643795',
       '807015863', '933815613', '499710590', '120847157', '53909146',
       '2236667932', '2123309722', '301242089', '237351106', '461558540',
       '417230415', '156898322', '127309180', '313113297', '173702135',
       '271666301', '305650299', '123216717', '479655659', '126191104',
       '344055883', '338422004', '68895644', '86176890', '403231558',
       '319546754', '61739839', '283359161', '76831876', '283332261',
       '307752576', '279737940', '212351890', '1304313953', '150500965',
       '246127838', '582863434', '58687425', '212109195', '382199619',
       '41210087', '231657891', '53729194', '244741137', '42485571',
       '37778188', '254218729', '53603447', '160035717', '164163229',
       '37091576', '284249832', '33381454', '184622518', '300983101',
       '121077868', '106919680', '136996305', '65719930', '229497852',
       '185550869', '54682594', '240580042', '1284942608', '71423324',
       '244891912', '132171975', '184706613', '184826429', '302006641',
       '330881149', '334733572', '366214458', '114546317', '290833204',
       '448500832', '136676504', '190625045', '79095270', '273194684',
       '333146475', '194902696', '311482393', '195918494', '248511839',
       '233671263', '199587884', '91781263', '383835984', '236060709',
       '189236868', '160845341', '588955257', '238350348', '187703102',
       '295307001', '138334433', '445590495', '286739476', '1122364376',
       '157136970', '137070925', '183273246', '184807630', '164856284',
       '704171068', '354614964', '279717388', '195628667', '221752937',
       '263280370', '213505179', '130419412', '155795783', '1553497987',
       '293466523', '711366595', '191448892', '85924992', '176103902',
       '121189256', '131746175', '244790012', '129314708', '331511413',
       '219196651', '170732845', '273914335', '179061440', '185236961',
       '171788484', '387080183', '264717480', '244928911', '97610446',
       '287278853', '887906111', '123473120', '295152154', '323455692',
       '240918092', '191873381', '284216603', '239411309', '265548837',
       '703301727', '244585109', '189476119', '277132266', '278920007',
       '222410722', '185392587', '202452860', '1608164312', '624101957',
       '148461629', '47093942', '380319238', '209106362', '53987404',
       '115331792', '225093344', '84697729', '159240673', '170709584',
       '154356956', '723043854', '247689123', '176474912', '235549288',
       '140430339', '85559365', '146223492', '187701588', '154863153',
       '191333656', '253650850', '223064273', '170413877', '218320587',
       '141720999', '187339835', '198365537', '186104310', '177503916',
       '71095708', '112436403', '203436468', '93367537', '106249219',
       '181382590', '91473363', '121871870', '73513683', '133895612',
       '96007391'], dtype=object)

In [10]:
#there's a funky value in our streams column that's gotta go.
value_to_drop = 'BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3'
s23 = s23[s23['streams'] != value_to_drop]

In [11]:
s23['streams'] = s23['streams'].astype(int)

In [12]:
#some adjustments need to be made to our oldies metrics to make them compatible with s23
s23['danceability_%'] = s23['danceability_%'] /100
s23['energy_%'] = s23['energy_%'] /100
s23['speechiness_%'] = s23['speechiness_%'] /100
s23['instrumentalness_%'] = s23['instrumentalness_%'] /100
s23['liveness_%'] = s23['liveness_%'] /100
s23['valence_%'] = s23['valence_%'] /100
s23['acousticness_%'] = s23['acousticness_%'] /100

In [13]:
s23.rename(columns={'danceability_%': 'danceability', 'energy_%': 'energy', 'speechiness_%': 'speechiness', 'instrumentalness_%': 'instrumentalness', 'liveness_%': 'liveness', 'valence_%': 'valence', 'acousticness_%': 'acousticness', 'bpm': 'tempo'}, inplace=True)

In [14]:
#check it worked
s23.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,tempo,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,0.80,0.89,0.83,0.31,0.00,0.08,0.04
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,0.71,0.61,0.74,0.07,0.00,0.10,0.04
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,0.51,0.32,0.53,0.17,0.00,0.31,0.06
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,0.55,0.58,0.72,0.11,0.00,0.11,0.15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,0.65,0.23,0.80,0.14,0.63,0.11,0.06

In [16]:
#predicting streams of oldies using LinearRegression
from sklearn.linear_model import LinearRegression

features = ['tempo', 'danceability', 'valence', 'energy', 'acousticness', 'instrumentalness', 'liveness', 'speechiness']
target = 'streams'

X_train = s23[features]
y_train = s23[target]

X_test = oldies[features]

model = LinearRegression()
model.fit(X_train, y_train)

predicted_streams = model.predict(X_test)

oldies['predicted_streams'] = predicted_streams

In [21]:
#testing accuracy
s23_sample_count = 952

# Downsample oldies to match the sample count in s23
oldies_downsampled = oldies.sample(n=s23_sample_count, random_state=42)

actual_streams_s23 = s23['streams']
predicted_streams_oldies = oldies_downsampled['predicted_streams']

mse = mean_squared_error(actual_streams_s23, predicted_streams_oldies)
print(f"Mean Squared Error (MSE): {mse}")

r_squared = r2_score(actual_streams_s23, predicted_streams_oldies)
print(f"R-squared (R^2): {r_squared}")

Mean Squared Error (MSE): 3.3326367130777184e+17
R-squared (R^2): -0.03823928036485813

This is pretty bad, suggesting Linear regression model is not the best for our task.

In [32]:
#Let's try a random forest model.
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

features = ['tempo', 'danceability', 'valence', 'energy', 'acousticness', 'instrumentalness', 'liveness', 'speechiness']
target = 'streams'

X_train_s23, X_test_s23, y_train_s23, y_test_s23 = train_test_split(s23[features], s23[target], test_size=0.2, random_state=42)

model_s23 = RandomForestRegressor(n_estimators=100, random_state=42)
model_s23.fit(X_train_s23, y_train_s23)

y_pred_s23 = model_s23.predict(X_test_s23)

mse_s23 = mean_squared_error(y_test_s23, y_pred_s23)
r_squared_s23 = r2_score(y_test_s23, y_pred_s23)
mae_s23 = mean_absolute_error(y_test_s23, y_pred_s23)

print("Evaluating 's23' dataset:")
print(f"Mean Squared Error (MSE) for 's23': {mse_s23}")
print(f"R-squared (R²) for 's23': {r_squared_s23}")
print(f"Mean Absolute Error (MAE) for 's23': {mae_s23}")

Evaluating 's23' dataset:
Mean Squared Error (MSE) for 's23': 2.7827818830693325e+17
R-squared (R²) for 's23': -0.13679070790572467
Mean Absolute Error (MAE) for 's23': 398895192.24225134

Relatively better, but still not good. Another model must be considered.